export AS1

CDIR=../common

EXE=uvtFrameIntegration	

SOURCES=main.cpp $(CDIR)/uvtUtils.cpp uvtFrameIntegration.cpp $(CDIR)/DataInfo.cpp $(CDIR)/spMatrix.cpp $(CDIR)/fft.cpp

include $(AS1)/uvit/makefile.common
