
export AS1
CDIR=../common


EXE=uvtCentroidBias	

SOURCES=main.cpp $(CDIR)/uvtUtils.cpp uvtCentroidBias.cpp $(CDIR)/DataInfo.cpp $(CDIR)/caldb_Handler.cpp $(CDIR)/spMatrix.cpp


include $(AS1)/uvit/makefile.common
