export AS1
INCLUDE1 = -I. -I../common/ -I../../../include/   
CDIR=../common
SRCDIR=..


EXE=ImageFrameGen	

SOURCES=main.cpp ImageFrameGen.cpp DataIngest.cpp   $(CDIR)/DataInfo.cpp $(CDIR)/uvtUtils.cpp  $(CDIR)/fft.cpp   $(CDIR)/caldb_Handler.cpp $(CDIR)/Directory.cpp $(CDIR)/spMatrix.cpp   
 
include $(AS1)/uvit/makefile.common

