export AS1
CDIR=../common

EXE=uvtRefFrameCal	

SOURCES=main.cpp $(CDIR)/uvtUtils.cpp uvtRefFrameCal.cpp $(CDIR)/DataInfo.cpp $(CDIR)/spMatrix.cpp 

OBJECTS=$(SOURCES:.cpp=.o)
include $(AS1)/uvit/makefile.common


