export AS1
CDIR=../common

EXE=uvtComputeDrift	

SOURCES=main.cpp $(CDIR)/uvtUtils.cpp uvtComputeDrift.cpp $(CDIR)/DataInfo.cpp $(CDIR)/spMatrix.cpp $(CDIR)/fft.cpp $(CDIR)/caldb_Handler.cpp $(CDIR)/transform.cpp

include $(AS1)/uvit/makefile.common
	

