export AS1
CDIR=../common


EXE=uvtDetectStar	

SOURCES=main.cpp $(CDIR)/uvtUtils.cpp uvtDetectStar.cpp $(CDIR)/DataInfo.cpp $(CDIR)/spMatrix.cpp 

OBJECTS=$(SOURCES:.cpp=.o)
include $(AS1)/uvit/makefile.common


