
export AS1
CDIR=../common


EXE=uvtDetectDistCorr	

SOURCES=main.cpp $(CDIR)/uvtUtils.cpp uvtDetectDistCorr.cpp $(CDIR)/DataInfo.cpp $(CDIR)/caldb_Handler.cpp $(CDIR)/spMatrix.cpp

include $(AS1)/uvit/makefile.common
