export AS1
CDIR=../common

EXE=uvtCentroidCorr

SOURCES=main.cpp $(CDIR)/uvtUtils.cpp uvtCentroidCorr.cpp $(CDIR)/DataInfo.cpp $(CDIR)/caldb_Handler.cpp $(CDIR)/spMatrix.cpp

include $(AS1)/uvit/makefile.common
