export AS1
CDIR=../common

EXE=uvtFullFrameAst	

SOURCES=main.cpp $(CDIR)/uvtUtils.cpp uvtFullFrameAst.cpp $(CDIR)/DataInfo.cpp $(CDIR)/Attitude.cpp $(CDIR)/caldb_Handler.cpp  $(CDIR)/Database.cpp  $(CDIR)/spMatrix.cpp
lib_sql=-lsqlite3
include $(AS1)/uvit/makefile.common

