export AS1
EXE=uvtQEMCPCorr	
CDIR=../common

SOURCES=main.cpp $(CDIR)/uvtUtils.cpp uvtQEMCPCorr.cpp $(CDIR)/DataInfo.cpp $(CDIR)/spMatrix.cpp $(CDIR)/caldb_Handler.cpp 

OBJECTS=$(SOURCES:.cpp=.o)
include $(AS1)/uvit/makefile.common


