export AS1

CDIR=../common


EXE=uvtOpticAssDistCorrL2	

SOURCES=main.cpp $(CDIR)/uvtUtils.cpp uvtOpticAssDistCorrL2.cpp $(CDIR)/DataInfo.cpp $(CDIR)/caldb_Handler.cpp $(CDIR)/spMatrix.cpp

include $(AS1)/uvit/makefile.common
