CDIR=../common

export AS1
EXE=uvtMaskBadPix	

SOURCES=main.cpp $(CDIR)/uvtUtils.cpp uvtMaskBadPix.cpp $(CDIR)/DataInfo.cpp $(CDIR)/spMatrix.cpp $(CDIR)/caldb_Handler.cpp 
include $(AS1)/uvit/makefile.common

