export AS1

CDIR=../common

EXE=uvtShiftRot	

SOURCES=main.cpp $(CDIR)/uvtUtils.cpp uvtShiftRot.cpp  $(CDIR)/DataInfo.cpp $(CDIR)/transform.cpp $(CDIR)/spMatrix.cpp $(CDIR)/caldb_Handler.cpp

include $(AS1)/uvit/makefile.common
