export AS1
CDIR=../common

EXE=uvtDetectDistCorrL2	

SOURCES=main.cpp $(CDIR)/uvtUtils.cpp uvtDetectDistCorrL2.cpp $(CDIR)/DataInfo.cpp  $(CDIR)/caldb_Handler.cpp $(CDIR)/spMatrix.cpp

include $(AS1)/uvit/makefile.common
