export AS1

CDIR=../common

EXE=uvtFlatFieldCorr	

SOURCES=main.cpp $(CDIR)/uvtUtils.cpp uvtFlatFieldCorr.cpp $(CDIR)/DataInfo.cpp $(CDIR)/caldb_Handler.cpp $(CDIR)/spMatrix.cpp

include $(AS1)/uvit/makefile.common
	


