export AS1

CDIR=../common


EXE=uvtOpticAssDistCorr

SOURCES=main.cpp $(CDIR)/uvtUtils.cpp uvtOpticAssDistCorr.cpp $(CDIR)/DataInfo.cpp $(CDIR)/caldb_Handler.cpp $(CDIR)/spMatrix.cpp
include $(AS1)/uvit/makefile.common
